version: "3"

services:
  app-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    command: /bin/api-app
    environment:
      DB_URI: "mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017"
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017-27019:27017-27019"
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"
